### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by hardR0ck** [P1llus/ArcSight-Rest#1]
Hi 
I am unable to import the arsightrest lib, can you please have a look in to this
 python
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import arcsightrest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "arcsightrest.py", line 130
    for field, result in zip(events['fields'], results)
      ^

**Comment by P1llus** [comment]
Hello @hardR0ck .

It is working just fine here. Can you test with a updated version of python 2.6 or try a python 3 version?

Might be that there has been a function that has been written to support 3, but broken the backwards compability for 2.

If it does not work for you with a fully updated 2, and only with 3, i will look into it to make sure it can support both versions.

If you got any other bugs, feedback or feature requests, just let me know!


EDIT:
Here is me importing it on 2.7:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import arcsightrest
>>> 
```

**Comment by P1llus** [comment]
Not able to introduce the problem on anything v2.7 and upwards.
