### ISSUE TITLE
Can't login to arcsight server

### ISSUE THREAD

**Issue by estemendoza** [P1llus/ArcSight-Rest#4]
Hi, thanks for creating this library to interact with Arcsight.

I am using python 3.6 and when I tried to login to Arcsight server, I get this error:

```
~/.virtualenvs/blabla/lib/python3.6/site-packages/arcsightrest.py in __init__(self, username, password, disable_insecure_warning)
     34             }, is_json=False)
     35         r.raise_for_status()
---> 36         loginrequest = untangle.parse(r.content)
     37         self.token = loginrequest.ns3_loginResponse.ns3_return.cdata
     38 

~/.virtualenvs/blabla/lib/python3.6/site-packages/untangle.py in parse(filename, **parser_features)
    180             parser.parse(filename)
    181         else:
--> 182             parser.parse(StringIO(filename))
    183 
    184     return sax_handler.root

TypeError: initial_value must be str or None, not bytes
```

Any ideas what this could be?

**Comment by P1llus** [comment]
@estemendoza it seems like a Pull request is not in your repository, https://github.com/P1llus/ArcSight-Rest/pull/2 this fixes that. Temp fix is that you can change r.content to r.text.

Please do a git pull and it should work :)

If you used pypi:
I added a version 1.3 on pypi, most likely you got it from pip, totally forgot that they changed their uploading procedure.

This will resolve your issue: `pip install arcsightrest --upgrade`

**Comment by estemendoza** [comment]
Awesome, thanks!
