### ISSUE TITLE
Implement logout

### ISSUE THREAD

**Issue by Fx4-X** [P1llus/ArcSight-Rest#5]
Could you please Implement logout option?

**Comment by P1llus** [comment]
Sure! I have plans for a proper rewrite of this, to support different versions of the Logger API, but a logout would not take long. Will plan it for this weekend!

**Comment by P1llus** [comment]
As mentioned in the other issue you had posted, a brand new version has been released, which will be the last one on this specific repo. The new version has all functionality included in it, including logout.

To follow the future updates please refer to the readme for updates!
